### ISSUE TITLE
WFFM Forms deleted after conversion

### ISSUE THREAD

**Issue by ahiyalala** [afaniuolo/WFFM-Conversion-Tool#19]
Is there a way to toggle this off? I don't think it is a good idea to remove them when you want to cross check which fields are actually missing.

**Comment by afaniuolo** [comment]
Hi @ahiyalala ,

Reading your description of the issue, it seems that you are using the tool configuring the source master database and the destination master database connection strings using the same database.

While the tool should be able to convert items in this scenario, it is recommended to use it with different source and destination databases, to avoid that the conversion write process (intended to write to a separate destination database) overrides your source items.

Because the tool doesn't require running Sitecore instances, you can easily create a copy of your source master database and use it as a destination master database. In this way, your source and your destination databases are two separate databases.

**Comment by ahiyalala** [comment]
I see. Thanks for that response! Is the same behavior expected on the form data that will be migrated as well?

**Comment by afaniuolo** [comment]
Sitecore Forms stores the data to a different SQL database than the WFFM module (the schema of the two databases is different), so you are probably already using different connection strings for the stored forms data.

**Comment by ahiyalala** [comment]
Upon checking, the Sitecore Form counterpart uses the Item ID of the original WFFM form. I'm a bit curious now how does pointing to a different Database source prevent an override since the GUID of WFFM Form A under Database Source will be the same GUID for the WFFM Form under Database Destination.

**Comment by afaniuolo** [comment]
It doesn't prevent an override on the destination database, but with this approach you keep your source database unchanged. You can toggle the connection string of the master database in your Sitecore instance if you want to check source items or destination items. It would probably be easier if you can setup two separate Sitecore instances, one that uses the source master db and one that uses the destination master db.

The conversion process keeps the original item IDs to facilitate the submitted forms data migration, because the forms data is stored in the WFFM database using references to items and fields IDs.

**Comment by ahiyalala** [comment]
Yes, I thought so on why you chose to keep the original ID. However, wouldn't this pose a challenge in a real-world scenario wherein the conversion would most likely take place only on the same instance?

**Comment by afaniuolo** [comment]
The WFFM module has been deprecated starting with Sitecore 9.1, the first target version that this tool officially support to migrate to.

The tool is mainly meant to be used in the context of a Sitecore upgrade project, where the source and the destination instances have completely different Sitecore versions (for example upgrading from Sitecore 8.2 to Sitecore 9.3) and the WFFM module doesn't exist on the destination upgraded instance.

I just realized that you are working on one of the few versions of Sitecore (9.0.x) where WFFM and Sitecore Forms coesists together. While the tool has been officially tested with Sitecore target versions equal or higher of SC 9.1, the conversion should still work but I recommend to execute it following the approach commented before, using two separate instances.

**Comment by ahiyalala** [comment]
I understand now. All in all, the tool works as I've expected, at least almost. 😂 Thanks!
